name: ms_list_utils
description: Novas funções para lidar com listas. Com suporte an extensions
version: 0.4.0
homepage: https://github.com/Marcus-Software/ms_list_utils

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dev_dependencies:
  test: ^1.16.7
  flutter_lints: ^1.0.4

flutter:
